name: PyStand

on:
  push:
  pull_request:
    types: [ opened, reopened, ready_for_review ]

env:
  PYSTAND_VERSION: v1.0.7
  BUILD_TYPE: Release

jobs:
  build-msvc:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      github.event.pull_request.draft == false

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { generator: Visual Studio 17 2022, arch: Win32, subsystem: GUI }
          - { generator: Visual Studio 17 2022, arch: Win32, subsystem: CLI }
          - { generator: Visual Studio 17 2022, arch: x64, subsystem: GUI }
          - { generator: Visual Studio 17 2022, arch: x64, subsystem: CLI }

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure
      run: >
        cmake
        -G "${{ matrix.generator }}"
        -A ${{ matrix.arch }}
        -B build
        ${{ matrix.subsystem == 'GUI' && '-DPYSTAND_CONSOLE=OFF' || '-DPYSTAND_CONSOLE=ON' }}

    - name: Build
      run: |
        cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PyStand-${{ env.PYSTAND_VERSION }}-${{ matrix.arch }}-${{ matrix.subsystem }}
        path: build/${{ env.BUILD_TYPE }}

  build-gcc:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      github.event.pull_request.draft == false

    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: mingw32, subsystem: GUI }
          - { sys: mingw32, subsystem: CLI }
          - { sys: mingw64, subsystem: GUI }
          - { sys: mingw64, subsystem: CLI }

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MinGW-w64
      run: |
        if ( '${{ matrix.sys }}' -eq 'mingw32' )
        {
          Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/7.5.0-7.0.0-r1/winlibs-i686-posix-dwarf-gcc-7.5.0-mingw-w64-7.0.0-r1.7z -OutFile ${{ matrix.sys }}.7z
        }
        else
        {
          Invoke-WebRequest -Uri https://github.com/brechtsanders/winlibs_mingw/releases/download/7.5.0-7.0.0-r1/winlibs-x86_64-posix-seh-gcc-7.5.0-mingw-w64-7.0.0-r1.7z -OutFile ${{ matrix.sys }}.7z
        }
        7z x ${{ matrix.sys }}.7z
        "${{ github.workspace }}\${{ matrix.sys }}\bin" >> $env:GITHUB_PATH

    - name: Configure
      run: >
        cmake
        -G "MinGW Makefiles"
        -B build
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        ${{ matrix.subsystem == 'GUI' && '-DPYSTAND_CONSOLE=OFF' || '-DPYSTAND_CONSOLE=ON' }}

    - name: Build
      run: |
        cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PyStand-${{ env.PYSTAND_VERSION }}-${{ matrix.sys }}-${{ matrix.subsystem }}
        path: build\PyStand.exe

  release:
    runs-on: windows-latest

    needs: [ build-msvc, build-gcc ]

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      if: startsWith(github.ref, 'refs/tags/')

    - name: List downloaded files
      if: startsWith(github.ref, 'refs/tags/')
      run: ls -R

    - name: Create archives
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        7z a PyStand-${{ env.PYSTAND_VERSION }}-Win32-CLI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-Win32-CLI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-Win32-GUI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-Win32-GUI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-x64-CLI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-x64-CLI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-x64-GUI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-x64-GUI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-mingw32-CLI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-mingw32-CLI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-mingw32-GUI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-mingw32-GUI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-mingw64-CLI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-mingw64-CLI\*
        7z a PyStand-${{ env.PYSTAND_VERSION }}-mingw64-GUI.zip .\PyStand-${{ env.PYSTAND_VERSION }}-mingw64-GUI\*

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        generate_release_notes: true
        files: |
          PyStand*.zip
