name: PyStand

on: [push, pull_request]

env:
  PYSTAND_VERSION: v1.0.6

jobs:
  build:
    if: >-
      ! contains(toJSON(github.event.commits.*.message), '[skip ci]') &&
      ! contains(toJSON(github.event.commits.*.message), '[skip github]')
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {generator: Visual Studio 17 2022, arch: Win32, subsystem: GUI, console: OFF}
          - {generator: Visual Studio 17 2022, arch: Win32, subsystem: CLI, console: ON}
          - {generator: Visual Studio 17 2022, arch: x64, subsystem: GUI, console: OFF}
          - {generator: Visual Studio 17 2022, arch: x64, subsystem: CLI, console: ON}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Configure
      run: |
        cmake -G "${{ matrix.generator }}" -A ${{ matrix.arch }} -DPYSTAND_CONSOLE=${{ matrix.console }} -B build
    - name: Build
      run: cmake --build build --config Release 
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PyStand-${{ env.PYSTAND_VERSION }}-${{ matrix.arch }}-${{ matrix.subsystem }}
        path: build/Release

  release:
    needs: [build]
    runs-on: windows-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          artifacts/PyStand-${{ env.PYSTAND_VERSION }}-Win32-GUI/PyStand-${{ env.PYSTAND_VERSION }}-Win32-GUI.zip
          artifacts/PyStand-${{ env.PYSTAND_VERSION }}-Win32-CLI/PyStand-${{ env.PYSTAND_VERSION }}-Win32-CLI.zip
          artifacts/PyStand-${{ env.PYSTAND_VERSION }}-x64-GUI/PyStand-${{ env.PYSTAND_VERSION }}-x64-GUI.zip
          artifacts/PyStand-${{ env.PYSTAND_VERSION }}-x64-GUI/PyStand-${{ env.PYSTAND_VERSION }}-x64-GUI.zip
